# Use official Python base image
FROM python:3.12

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV VIRTUAL_ENV=/venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# Install system dependencies & create virtual environment
RUN apt-get update && \
    apt-get install -y --no-install-recommends build-essential && \
    apt-get install -y --no-install-recommends build-essential redis && \
    python -m venv $VIRTUAL_ENV

# Set working directory
WORKDIR /app

# Copy requirements first to leverage Docker cache
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy application source code
COPY src ./src
COPY src ./tests
# DEV COPY src ./dev

# Expose the port your app runs on
EXPOSE 8080

# Run the application
CMD ["python", "src/app.py"]